<eclipse>
<message date="1/1/1986" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1986" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
       1968 KBYTES                                                       
</message>
<message date="1/1/1986" time="0.00000000000000">
 UNSPECIFIED TOPS VALUES OBTAINED BY ADDING DZ                           
 TO TOPS VALUE FOR LAYER ABOVE                                           
</message>
<message date="1/1/1986" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 BLOCK CENTRE TRANSMISSIBILITIES TO BE CALCULATED                        
 USING  OLDTRAN                                                          
</message>
<message date="1/1/1986" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 5000                                          
</message>
<message date="1/1/1986" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
       7060 KBYTES                                                       
</message>
<message date="1/1/1986" time="0.00000000000000">
    60302 CHARACTER VARIABLES USED                                       
</message>
<message date="1/1/1986" time="0.00000000000000">
 FU_OR1 INITIALISED AS USER DEFINED QUANTITY NO. 1                       
</message>
<message date="1/1/1986" time="0.00000000000000">
 FU_OR1 ASSIGNMENT PROCESSED. UPDATE STATUS SET TO OFF.                  
</message>
<message date="1/1/1986" time="0.00000000000000">
 FU_OR2 INITIALISED AS USER DEFINED QUANTITY NO. 2                       
</message>
<message date="1/1/1986" time="0.00000000000000">
 FU_OR2 ASSIGNMENT PROCESSED. UPDATE STATUS SET TO OFF.                  
</message>
<message date="1/1/1986" time="0.00000000000000">
 FU_MIN INITIALISED AS USER DEFINED QUANTITY NO. 3                       
</message>
<message date="1/1/1986" time="0.00000000000000">
 FU_MIN DEFINITION PARSED. UPDATE STATUS SET TO ON.                      
</message>
<message date="1/1/1986" time="0.00000000000000">
 FU_MAX INITIALISED AS USER DEFINED QUANTITY NO. 4                       
</message>
<message date="1/1/1986" time="0.00000000000000">
 FU_MAX DEFINITION PARSED. UPDATE STATUS SET TO ON.                      
</message>
<message date="1/1/1986" time="0.00000000000000">
 FU_SUM INITIALISED AS USER DEFINED QUANTITY NO. 5                       
</message>
<message date="1/1/1986" time="0.00000000000000">
 FU_SUM DEFINITION PARSED. UPDATE STATUS SET TO ON.                      
</message>
<message date="1/1/1986" time="0.00000000000000">
 FU_AVEA INITIALISED AS USER DEFINED QUANTITY NO. 6                      
</message>
<message date="1/1/1986" time="0.00000000000000">
 FU_AVEA DEFINITION PARSED. UPDATE STATUS SET TO ON.                     
</message>
<message date="1/1/1986" time="0.00000000000000">
 FUGWRAT INITIALISED AS USER DEFINED QUANTITY NO. 7                      
</message>
<message date="1/1/1986" time="0.00000000000000">
 FUGWRAT DEFINITION PARSED. UPDATE STATUS SET TO ON.                     
</message>
<message date="1/1/1986" time="0.00000000000000">
 FUGLRAT INITIALISED AS USER DEFINED QUANTITY NO. 8                      
</message>
<message date="1/1/1986" time="0.00000000000000">
 FUGLRAT DEFINITION PARSED. UPDATE STATUS SET TO ON.                     
</message>
<message date="1/1/1986" time="0.00000000000000">
 FUGGRAT INITIALISED AS USER DEFINED QUANTITY NO. 9                      
</message>
<message date="1/1/1986" time="0.00000000000000">
 FUGGRAT DEFINITION PARSED. UPDATE STATUS SET TO ON.                     
</message>
<message date="1/1/1986" time="0.00000000000000">
 FU_OR5 INITIALISED AS USER DEFINED QUANTITY NO. 10                      
</message>
<message date="1/1/1986" time="0.00000000000000">
 FU_OR5 ASSIGNMENT PROCESSED. UPDATE STATUS SET TO OFF.                  
</message>
<message date="1/1/1986" time="0.00000000000000">
  ARGUMENT NO. 3: OIL RATE TARGET                                        
  INITIALISED AS USER  DEFINED QUANTITY  FU_OR1                          
  IN THE CONTROL DATA KEYWORD  GCONPROD                                  
  FOR GROUP G1.                                                          
</message>
<message date="1/1/1986" time="0.00000000000000">
  ARGUMENT NO. 3: OIL RATE TARGET                                        
  INITIALISED AS USER  DEFINED QUANTITY  FU_OR2                          
  IN THE CONTROL DATA KEYWORD  GCONPROD                                  
  FOR GROUP G2.                                                          
</message>
<message date="1/1/1986" time="0.00000000000000">
 ******************************************                              
 * WELL P20      HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME      0.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="1/1/1986" time="0.00000000000000">
 ******************************************                              
 * WELL P24      HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME      0.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="1/1/1986" time="0.00000000000000">
 **********************************                                      
 * GROUP G2       CANNOT MEET ITS *                                      
 *  OIL   PRODUCTION TARGET       *                                      
 * AFTER TIME      0.00   DAYS  . *                                      
 **********************************                                      
</message>
<message date="11/4/1986" time="100.00000000000000">
  ARGUMENT NO. 3: OIL RATE TARGET                                        
  INITIALISED AS USER  DEFINED QUANTITY  FU_MIN                          
  IN THE CONTROL DATA KEYWORD  GCONPROD                                  
  FOR GROUP G*.                                                          
</message>
<message date="11/4/1986" time="100.00000000000000">
 **********************************************                          
 * WELL P20      HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME    100.00   DAYS  .              *                          
 **********************************************                          
</message>
<message date="11/4/1986" time="100.00000000000000">
 **********************************                                      
 * GROUP G2       CAN MEET ITS    *                                      
 *  OIL   PRODUCTION TARGET       *                                      
 * AFTER TIME    100.00   DAYS  . *                                      
 **********************************                                      
</message>
<message date="20/7/1986" time="200.00000000000000">
  ARGUMENT NO. 3: OIL RATE TARGET                                        
  INITIALISED AS USER  DEFINED QUANTITY  FU_OR5                          
  IN THE CONTROL DATA KEYWORD  GCONPROD                                  
  FOR GROUP G1.                                                          
</message>
<message date="28/10/1986" time="300.00000000000000">
  ARGUMENT NO. 3: OIL RATE TARGET                                        
  INITIALISED AS USER  DEFINED QUANTITY  FU_AVEA                         
  IN THE CONTROL DATA KEYWORD  GCONPROD                                  
  FOR GROUP G1.                                                          
</message>
<message date="5/2/1987" time="400.00000000000000">
  ARGUMENT NO. 3: OIL RATE TARGET                                        
  INITIALISED AS USER  DEFINED QUANTITY  FU_MAX                          
  IN THE CONTROL DATA KEYWORD  GCONPROD                                  
  FOR GROUP G1.                                                          
</message>
<message date="16/5/1987" time="500.00000000000000">
  ARGUMENT NO. 3: OIL RATE TARGET                                        
  UN-INITIALISED AS USER  DEFINED QUANTITY                               
  IN THE CONTROL DATA KEYWORD  GCONPROD                                  
  FOR GROUP G*.                                                          
</message>
<message date="16/5/1987" time="500.00000000000000">
  ARGUMENT NO. 4: WATER RATE TARGET                                      
  INITIALISED AS USER  DEFINED QUANTITY  FUGWRAT                         
  IN THE CONTROL DATA KEYWORD  GCONPROD                                  
  FOR GROUP G*.                                                          
</message>
<message date="16/5/1987" time="500.00000000000000">
 **********************************************                          
 * WELL P24      HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME    500.00   DAYS  .              *                          
 **********************************************                          
</message>
<message date="24/8/1987" time="600.00000000000000">
  ARGUMENT NO. 4: WATER RATE TARGET                                      
  UN-INITIALISED AS USER  DEFINED QUANTITY                               
  IN THE CONTROL DATA KEYWORD  GCONPROD                                  
  FOR GROUP G*.                                                          
</message>
<message date="24/8/1987" time="600.00000000000000">
  ARGUMENT NO. 5: GAS RATE TARGET                                        
  INITIALISED AS USER  DEFINED QUANTITY  FUGGRAT                         
  IN THE CONTROL DATA KEYWORD  GCONPROD                                  
  FOR GROUP G*.                                                          
</message>
<message date="2/12/1987" time="700.00000000000000">
  ARGUMENT NO. 5: GAS RATE TARGET                                        
  UN-INITIALISED AS USER  DEFINED QUANTITY                               
  IN THE CONTROL DATA KEYWORD  GCONPROD                                  
  FOR GROUP G*.                                                          
</message>
<message date="2/12/1987" time="700.00000000000000">
  ARGUMENT NO. 6: LIQUID RATE TARGET                                     
  INITIALISED AS USER  DEFINED QUANTITY  FUGLRAT                         
  IN THE CONTROL DATA KEYWORD  GCONPROD                                  
  FOR GROUP G*.                                                          
</message>
</eclipse>
